### ISSUE TITLE
add mypy version flag

### ISSUE THREAD

**Issue by Psychokiller1888** [jpetrucciani/mypy-check#12]
Hi!

could you add a flag to specify the mypy version? Your latest release updated it to 0.920, and mypy 0.920 does not ship with type hints anymore, so, well, most of my checks broke because they don't have a solution for CI yet.... So if we could specify the version in your action, it would be sweet :-)

**Comment by jpetrucciani** [comment]
Hey there! Does `0.910` work for you? Technically you can specify tags in your workflows, like so:

```yaml
uses: jpetrucciani/mypy-check@0.910
```

And if there is a tag I'm missing that works better, I can definitely add that! As is, it'll now automatically update this repo with any updates to the mypy package as they come out. But I would love to retain tags where necessary

**Comment by Psychokiller1888** [comment]
Well ,to be honest I did not even try to use @0.900 or 0.910. I'm pretty sure it works, because I'm now manually using mypy 0.900. My point was keeping your action uptodate, but be able to specify what mypy version it uses if you get what I mean

And... Thanks for your answer by the way! Wish you some nice winter holidays
